language: android
android:
  components:
    - tools 
    - tools 
    - platform-tools
    - build-tools-25.0.2
    - extra-android-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-gcm
    - extra-google-m2repository
    - android-25

sudo: required

jdk:
  - oraclejdk8

install: true

before_script:
  - chmod 777 /ParkingSpotFinder/gradlew

script:
  - cd /ParkingSpotFinder && ./gradlew assembleRelease --stacktrace

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"